### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by bounav** [ArcadeHacker/PVM-BVM-Monitor-ROM-Preservation#1]
Hello,

1. What's the best way to contribute ROMs to this repository? I'm thinking pull requests would make sense? 
2. How about adding README.md file to the repository and/or a few wiki pages to describe the project a little bit more and give instruction on how to create backups of the ROMs? (I'd happily help with that)

I've got the dumps of ROMs for 14G5E and 20G1E to contribute.

**Comment by ArcadeHacker** [comment]
Thanks and apologies for the radio silence, adding you to the project.
